language: scala

scala:
    - 2.11.7

jdk:
    - oraclejdk8

script: sbt coverage test

# go faster on travis
sudo: false

notifications:
    email:
        - dmitry.krivaltsevich@zalando.de
        - cezary.lada.extern@zalando.de

env:
- COVERALLS_TOKEN=token
